// Rachel Perlman & Dan Pasquale

// THIS CODE SCANS OVER ALL OF THE USERS' TWEET'S WORDS AND COUNTS THE NUMBER OF TIMES
// KEYWORDS ASSOCIATED WITH PARTICULAR THEMES ARE USED. THE CODE GENERATES A JSON
// FILE THAT CONTAINS A SET OF THEME SCORES FOR EACH POLITICIAN.

// require the NPM sentiment package and fs package
var fs = require('fs');
var allWords = require('./wordoutputtest.json');

// create array containing the twitter usernames of all politicians
var usernames = [
"SenatorRounds",
"SenatorBaldwin",
"SenJohnBarrasso",
"SenBennetCO",
"SenBlumenthal",
"RoyBlunt",
"CoryBooker",
"JohnBoozman",
"SenSherrodBrown",
"SenatorBurr",
"SenatorCantwell",
"SenCapito",
"SenatorCardin",
"SenatorCarper",
"SenBobCasey",
"BillCassidy",
"SaxbyChambliss",
"SenThadCochran",
"SenatorCollins",
"ChrisCoons",
"SenBobCorker",
"SenBobCorker",
"SenCortezMasto",
"SenTomCotton",
"MikeCrapo",
"SenTedCruz",
"SteveDaines",
"SenDonnelly",
"SenDuckworth",
"SenatorDurbin",
"SenatorEnzi",
"joniernst",
"SenFeinstein",
"SenatorFischer",
"JeffFlake",
"SenFranken",
"SenCoryGardner",
"SenGillibrand",
"GrahamBlog",
"ChuckGrassley",
"SenKamalaHarris",
"SenatorHassan",
"senorrinhatch",
"MartinHeinrich",
"SenatorHeitkamp",
"SenDeanHeller",
"maziehirono",
"SenJohnHoeven",
"PattyMurray",
"SenatorIsakson",
"timkaine",
"JohnKennedyLA",
"SenAngusKing",
"amyklobuchar",
"SenatorLankford",
"SenatorLeahy",
"SenMikeLee",
"Sen_JoeManchin",
"senmarkey",
"SenJohnMcCain",
"clairecmc",
"SenateMajLdr",
"SenatorMenendez",
"SenJeffMerkley",
"JerryMoran",
"lisamurkowski",
"ChrisMurphyCT",
"PattyMurray",
"SenBillNelson",
"RandPaul",
"sendavidperdue",
"SenGaryPeters",
"robportman",
"SenJackReed",

"SenatorRisch",
"SenPatRoberts",
"SenRonJohnson",
"SenatorRounds",
"marcorubio",
"BernieSanders",
"BenSasse",
"brianschatz",
"SenSchumer",
"SenatorTimScott",
"SenatorShaheen",
"SenShelby",
"SenStabenow",
"lutherstrange",
"SenDanSullivan",
"SenatorTester",
"SenJohnThune",
"ThomTillis",
"SenToddYoung",
"SenToomey",
"SenatorTomUdall",
"ChrisVanHollen",
"MarkWarner",
"SenWarren",
"SenWhitehouse",
"SenatorWicker",
"RonWyden",
"HurdOnTheHill ",
"JimPressOffice",
"Rep_Tom_Garrett",
"RepAbraham",
"RepBuddyCarter",
"RepCurbelo",
"repdavidkustoff",
"RepDonBacon",
"RepDWStweets",
"RepEspaillat",
"RepJohnDuncanJr",
"RepKClark",
"RepKenBuck",
"RepKihuen",
"repmarkpocan",
"RepMiaLove",
"RepMikeBishop",
"RepRubenGallego",
"RepRutherfordFL",
"RepSeanMaloney",
"RepTimWalz",
"USRepLong",
"USRepRickNolan",
"USRepRodney",
"WarrenDavidson",
"aguilarpete",
"AustinScottGA08",
"BennieGThompson",
"BettyMcCollum04",
"BillPascrell",
"boblatta",
"BradSherman",
"Call_Me_Dutch",
"cathymcmorris",
"chelliepingree",

"Clyburn",
"ConawayTX11",
"congbillposey",
"CongBoyle",
"CongCulberson",
"CongMikeSimpson",
"CongPalazzo",
"CongressmanGT",
"CongressmanHice",
"CongressmanRaja",
"CongressmanRuiz",
"dandonovan_ny",
"DarrellIssa",
"daveloebsack",
"davereichert",
"DesJarlaisTN04",
"DonaldNorcross",
"DorisMatsui",
"DrNealDunnFL2",
"DrPhilRoe",
"farenthold",
"FrankPallone",
"garretgraves",
"GerryConnolly",
"GKButterfield",
"GOPLeader",
"gracenapolitano",
"GreggHarper",
"GregoryMeeks",
"HerreraBeutler",
"JacksonLeeTX18",
"jahimes",
"janschakowsky",
"jaredpolis",
"jasoninthehouse",
"JeffFortenberry",
"Jim_Jordan",
"JimLangevin",
"JoaquinCastrotx",
"JudgeCarter",
"JudgeTedPoe",
"JuliaBrownley26",
"justinamash",
"keithellison",
"KeithRothfus",
"KenCalvert",
"LacyClayMO1",
"LamarSmithTX21",
"leezeldin",
"louiseslaughter",
"MacTXPress",
"MarioDB",
"MarkAmodeiNV2",
"MarshaBlackburn",
"MaxineWaters",
"michaelcburgess",

"mikecapuano",
"MikeKellyPA",
"NancyPelosi",
"nikiinthehouse",
"NitaLowey",
"NormaJTorres",
"NydiaVelazquez",
"PatrickMcHenry",
"PatTiberi",
"PeteOlson",
"PeterRoskam",
"PeterWelch",
"PeteSessions",
"Raul_Labrador",
"Rep_DevinNunes",
"Rep_Hunter",
"rep_stevewomack",
"RepAdams",
"RepAdamSchiff",
"RepAdamSmith",
"RepAdrianSmith",
"RepAlexMooney",
"RepAlGreen",
"RepAlLawsonJr",
"RepAmata",
"RepAndreCarson",
"RepAndyBarr",
"RepAndyBiggsAZ",
"RepAndyHarrisMD",
"RepAnnaEshoo",
"RepAnnieKuster",
"RepAnnWagner",
"RepAnthonyBrown",
"RepArrington",
"RepBarbaraLee",
"RepBarragan",
"RepBeatty",
"repbenraylujan",
"RepBera",
"RepBetoORourke",
"RepBillFlores",
"RepBillFoster",
"RepBillJohnson",
"RepBillShuster",
"RepBlainePress",
"repblumenauer",
"RepBobbyRush",
"RepBobGibbs",
"RepBonamici",
"RepBonnie",
"RepBost",
"RepBradWenstrup",
"RepBrady",
"RepBrianBabin",
"RepBrianFitz",
"RepBrianHiggins",
"RepBrianMast",
"RepBRochester",
"RepByrne",
"RepCarbajal",
"RepCarbajal",
"RepCardenas",
"RepCartwright",
"RepCharlieCrist",
"RepCharlieDent",

"RepCheri",
"RepChrisCollins",
"RepChrisSmith",
"RepChrisStewart",
"RepChuck",
"RepCicilline",
"RepClayHiggins",
"repcleaver",
"RepCohen",
"RepComstock",
"RepCuellar",
"RepCummings",
"RepDanKildee",
"RepDannyDavis",
"RepDarrenSoto",
"RepDaveBrat",
"RepDaveJoyce",
"repdavetrott",
"RepDavid",
"RepDavidEPrice",
"RepDavidRouzer",
"repdavidscott",
"RepDavidValadao",
"RepDavidYoung",
"RepDebDingell",
"RepDelBene",
"RepDennisRoss",
"RepDennyHeck",
"RepDerekKilmer",
"RepDeSantis",
"RepDeSaulnier",
"RepDianaDeGette",
"RepDianeBlack",
"repdinatitus",
"RepDLamborn",
"RepDonaldPayne",
"RepDonBeyer",
"repdonyoung",
"RepDougCollins",
"RepDrewFerguson",
"RepDwightEvans",
"RepEBJ",
"RepEdRoyce",
"RepEliotEngel",
"RepErikPaulsen",
"RepEsty",
"RepEvanJenkins",
"RepFilemonVela",
"RepFrankLucas",
"RepFredUpton",
"RepFrenchHill",
"RepGallagher",
"RepGaramendi",
"RepGeneGreen",
"RepGonzalez",
"RepGoodlatte",
"RepGosar",
"RepGraceMeng",
"repgregwalden",
"RepGrothman",
"RepGusBilirakis",
"RepGuthrie",
"RepGutierrez",
"RepGwenMoore",
"RepHalRogers",

"RepHanabusa",
"RepHankJohnson",
"RepHartzler",
"RepHastingsFL",
"RepHensarling",
"RepHolding",
"RepHuffman",
"RepHuizenga",
"RepHultgren",
"RepJackBergman",
"RepJackyRosen",
"RepJasonLewis",
"RepJasonLewis",
"RepJasonSmith",
"RepJBridenstine",
"RepJeffDenham",
"RepJeffDuncan",
"RepJeffries",
"RepJenniffer",
"RepJerryNadler",
"repjimcooper",
"RepJimCosta",
"RepJimmyPanetta",
"RepJimRenacci",
"RepJoeBarton",
"RepJoeCourtney",
"repjoecrowley",
"RepJoeKennedy",
"RepJoeWilson",
"RepJohnConyers",
"RepJohnDelaney",
"RepJohnFaso",
"RepJohnKatko",
"RepJohnLarson",
"RepJohnYarmuth",
"RepJoseSerrano",
"RepJoshG",
"RepJuanVargas",
"RepJudyChu",
"RepKarenBass",
"RepKathleenRice",
"RepKayGranger",
"RepKenMarchant",
"RepKevinBrady",
"RepKevinCramer",
"RepKevinYoder",
"RepKinzinger",
"RepKristiNoem",
"RepLaHood",
"RepLaMalfa",
"RepLanceNJ7",
"RepLarryBucshon",
"RepLawrence",
"RepLindaSanchez",
"RepLipinski",
"RepLizCheney",
"RepLloydDoggett",
"RepLoBiondo",
"RepLoisFrankel",
"RepLouBarletta",
"RepLouCorrea",
"RepLoudermilk",
"replouiegohmert",
"RepLowenthal",
"RepLujanGrisham",
"RepLukeMesser",
"RepLynnJenkins",
"RepMaloney",
"RepMarciaFudge",
"RepMarcyKaptur",
"RepMarkMeadows",
"RepMarkTakano",
"RepMarkWalker",
"RepMarthaRoby",
"RepMattGaetz",
"RepMcCaul",
"RepMcClintock",
"RepMcEachin",
"RepMcGovern",
"RepMcKinley",
"RepMcNerney",
"RepMcSally",
"RepMeehan",

"RepMGriffith",
"RepMikeBishop",
"RepMikeCoffman",
"RepMikeJohnson",
"RepMikeQuigley",
"RepMikeRogersAL",
"RepMikeTurner",
"RepMimiWalters",
"RepMoolenaar",
"RepMullin",
"RepNewhouse",
"RepOHalleran",
"RepPaulCook",
"RepPaulMitchell",
"RepPaulTonko",
"RepPerlmutter",
"RepPeteKing",
"RepPeterDeFazio",
"reppittenger",
"RepPoliquin",
"RepRaskin",
"RepRatcliffe",
"RepRaulGrijalva",
"RepRichardNeal",
"RepRichHudson",
"RepRichmond",
"RepRickAllen",
"RepRickCrawford",
"RepRickLarsen",
"RepRobinKelly",
"RepRobWoodall",
"RepRodBlum",
"RepRohrabacher",
"RepRoKhanna",
"RepRonKind",
"RepRooney",
"RepRooney",
"RepRoybalAllard",
"RepRussell",
"RepRWilliams",
"RepRyanCostello",
"RepSamGraves",
"repsandylevin",
"RepSanfordSC",
"RepSarbanes",
"RepSchneider",
"RepSchrader",
"RepScottPerry",
"RepScottPeters",
"RepScottTaylor",
"RepSeanDuffy",
"RepSheaPorter",
"RepShimkus",
"RepSinema",
"RepSires",
"RepSmucker",
"RepSpeier",
"RepStefanik",
"RepStephenLynch",
"RepStephMurphy",
"RepSteveChabot",
"RepStevePearce",
"RepSteveStivers",
"RepSusanDavis",
"RepSwalwell",
"RepTedBudd",
"RepTedDeutch",
"RepTedLieu",
"RepTedYoho",
"RepTenney",
"RepTerriSewell",
"RepThomasMassie",
"RepThompson",
"RepTimMurphy",
"RepTimRyan",
"RepTipton",
"RepTomEmmer",
"RepTomGraves",

"RepTomMacArthur",
"RepTomMarino",
"RepTomReed",
"RepTomRice",
"RepTomSuozzi",
"RepTrentFranks",
"RepTrentKelly",
"RepTrey",
"RepValDemings",
"RepVeasey",
"RepVisclosky",
"RepWalberg",
"RepWalorski",
"RepWalterJones",
"RepWebster",
"RepWesterman",
"RepWilson",
"RepYvetteClarke",
"RepZoeLofgren",
"Robert_Aderholt",
"RodneyDavis",
"rosadelauro",
"RosLehtinen",
"SamsPressShop",
"SanfordBishop",
"sethmoulton",
"SpeakerRyan",
"SteveKingIA",
"SteveKnight25",
"SteveScalise",
"SusanWBrooks",
"TGowdySC",
"ToddRokita",
"TomColeOK04",
"TulsiPress",
"TXRandy14",
"USRepGaryPalmer",
"USRepKCastor",
"USRepKeating",
"USRepMikeDoyle",
"VernBuchanan",
"virginiafoxx",
"WhipHoyer",
"realDonaldTrump",
"stevenmnuchin1",
"jeffsessions",
"SecretarySonny",
"RealBenCarson",
"SecretaryPerry",
"SecShulkin",
"SecretaryZinke",
"SecretaryRoss",
"SecPriceMD",
"SecElaineChao",
"BetsyDeVos",
"Reince",
"ScottPruittOK",
"nikkihaley",
"Linda_McMahon",
"mike_pence"
];

// Create an array of 17 themes that we defined by associating each theme with relevant key words
// We tried to choose themes that reflected some issues important to the public
var themes = 
[{theme: 'racism', keyWords: ['racism', 'africanamerican', 'blacklivesmatter', 'race', 'racial', 'KKK', 'ferguson', 'michael brown', 'eric garner', 'tamir rice']},

{theme: 'gender_equality', keyWords: ['gender equality', 'gender', 'genderbiasedlaws', 'genderpaygap', 'gender inequality', 'women', 'feminism', 'feminist', 'glass ceiling', 'pay gap', 'wage gap', 'sexist', 'sexism', 'womensmarch', 'fem2', 'bindersfullofwomen', 'bringbackourgirls', 'rapeculture', 'yesallwomen', 'everydaysexism', 'nastywoman']},

{theme: 'abortion', keyWords: ['abortion', 'planned parenthood', 'plannedparenthood', 'pro-life', 'prolife', 'prochoice', 'pro-choice','roe v. wade', 'fetus', 'defundpp', 'praytoendabortion', 'unwanted pregnancy', 'contraception']},

{theme: 'terrorism', keyWords: ['terrorism','terror', 'ISIS', 'san bernadino', '9/11', '9-11', 'hezbollah', 'al-qaeda', 'alqueda', 'boko haram', 'bokoharam', 'hostage', 'fundamentalist', 'extremist', 'bombing', 'air india', 'beslan', 'karrada', 'Gamboru']},

{theme: 'climate_change', keyWords: [ 'climatechange', 'warming', 'climate', 'climateaction', 'globalwarming', 'sealevel', 'greenhouse', 'carbon', 'co2', 'methane', '350ppm', 'inconvenienttruth', 'extremeweather', 'polarplunge']},

{theme: 'health_care', keyWords: ['health', 'healthcare', 'obamacare', 'ACA', 'affordablecareact', 'healthinsurance', 'preexistingconditions', 'medicaid', 'medicare', 'prescription', 'VAhospital', 'healthcarereform', 'walterreed', 'medical', 'hospital', 'doctor', 'doctors']},

{theme: 'immigration', keyWords: ['immigration', 'sanctuarycity', 'sanctuarycities','border','wall', 'buildthewall', 'alien', 'immigrant', 'immigrants', 'illegal', 'undocumented', 'citizenship', 'mexicans', 'border', 'borderscurity', 'amnesty', 'anchorbaby', 'anchorbabies', 'deport', 'deportation']},

{theme: 'LGBTQ_issues', keyWords: ['LGBTQ', 'gay', 'gaymarraige', 'gayrights','transgender','trans','lesbian', 'bisexual', 'DADT', 'DontAskDontTell', 'rainbowflag', 'loveislove', 'civilunion', 'homosexual', 'homophobia', 'genderidentity']},

{theme: 'gun_control', keyWords: ['gun control', 'guncontrol', 'gun', 'gun-related', 'background-checks', 'firearms', 'assault weapon', 'bear arms', 'second Amendment', 'orlando', 'mass shooting', 'pulse nightclub', 'sandy hook', 'san bernardino', 'paris attack']},

{theme: 'refugees', keyWords: ['refugees', 'refugee', 'refugeecrisis', 'Syrianrefugees' ]},

{theme: 'vaccinations', keyWords: ['vaccinations', 'vaccination', 'vaccines', 'antivax', 'vaccinate', 'vaccineswork']},

{theme: 'energy', keyWords: ['energy', 'wind', 'solar','oil','coal','geothermal', 'nuclearpower', 'fossilfuels', 'naturalgas', 'renewables', 'renewableenergy']},

{theme: 'police_brutality', keyWords: ['policebrutality', 'ferguson', 'michaelbrown', 'ericgarner', 'garner', 'tamirrice', 'tamir', 'excessiveforce', 'bodycameras', 'policeshootings', 'police', 'bluelivesmatter']},

{theme: 'prison_system', keyWords: ['prison', 'incarceration', 'incarcerated', 'jail', 'prisonreform', 'penal', 'deathpenalty', 'recidivism', 'criminaljustice', 'inmate', 'solitaryconfinement' ]},

{theme: 'marijuana', keyWords: ['marijuana', 'pot', 'decriminalization', 'medicalmarijuana']},

{theme: 'presidential_election_2016', keyWords: ['election2016', '2016election', 'lockherup','trump2016', 'basketofdeplorables', 'crookedhillary', 'imwithher', 'feelthebern', 'presidentialelection', 'feelthebern', 'presidentialdebates', 'presidentialdebate', 'vpdebate', 'trumppence', 'clinton', 'clintonkaine']},

{theme: 'trump', keyWords: ['trump', 'donald', 'thedonald', 'donaldtrump', 'trumptrain', 'makeamericagreatagain', 'realdonaldtrump', 'nevertrump', 'maga', 'tinyhands', 'donny', 'theapprentice']}];


// create empty object that will contain the theme's scores
score_obj = [];


// loops over users
for (var i = 0; i < usernames.length; i++){
    console.log(usernames[i]);
    
    // create array for theme scores that have been initialized to 0
    var theme_scores_array = 
    [{"theme":"racism","score": 0},
    {"theme":"gender_equality","score": 0},
    {"theme":"abortion","score": 0},
    {"theme":"terrorism","score": 0},
    {"theme":"climate_change","score": 0},
    {"theme":"health_care","score":0},
    {"theme":"immigration","score": 0},
    {"theme":"LGBTQ_issues","score": 0},
    {"theme":"gun_control","score": 0},
    {"theme":"refugees","score": 0},
    {"theme":"vaccinations","score": 0},
    {"theme":"energy","score": 0},
    {"theme":"police_brutality","score": 0},
    {"theme":"prison_system","score": 0},
    {"theme":"marijuana","score": 0},
    {"theme":"presidential_election_2016","score": 0},
    {"theme":"trump","score": 0}
    ];

    // loop over themes
    for (var x = 0; x < themes.length; x++){
       
        // loop over each username object
        //loop over length of sortedWords
        for (var w = 0; w < allWords[i].sortedWords.length; w++){
            
            // if the list of sortedwords contains any of the keywords, increase the score by that word count 
            //console.log(allWords[i].sortedWords[w]);
            if (themes[x].keyWords.includes(allWords[i].sortedWords[w].word)){
                theme_scores_array[x].score += allWords[i].sortedWords[w].count;
            }
        }
    }
    // create object to contain the theme score array associated with the particular user
    var this_score_obj = {
        "username": usernames[i],
        "theme_scores": theme_scores_array
    };
    
    // push the score object into the larger object containing all of the users' scores
    score_obj.push(this_score_obj);
    
}

// write a json file containing the resulting object
fs.appendFileSync('./theme_scores1.json', JSON.stringify(score_obj));

